version: '3.8'

services:
  # Server - Chat Service
  chat_service_api:
    container_name: chat_service_api
    image: peerprep_chat_service_api
    build: ./server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # local->container
      - ${EXPRESS_LOCAL_PORT}:${EXPRESS_DOCKER_PORT}
    depends_on:
        - chat_service_redis
    networks:
        - peerprep
# Redis - Chat Service
  chat_service_redis:
    container_name: chat_service_redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    networks:
      - peerprep

networks:
    peerprep:
        external: true



