version: '3.8'

services:
  # Redis - Chat Service
  chat_service_message_broker:
    container_name: chat_service_message_broker
    image: redis:7-bookworm
    networks:
      - peerprep
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: unless-stopped

  # Server - Chat Service
  chat_service_api:
    container_name: chat_service_api
    image: ghcr.io/cs3219-ay2324s1-g04/peerprep_chat_service_api
    build: .
    networks:
      - peerprep
    environment:
      REDIS_USERNAME: default
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: chat_service_message_broker
      REDIS_PORT: 6379
      REDIS_SHOULD_USE_TLS: false
      ROOM_SERVICE_MQ_USER: ${ROOM_SERVICE_MQ_USER}
      ROOM_SERVICE_MQ_PASSWORD: ${ROOM_SERVICE_MQ_PASSWORD}
      ROOM_SERVICE_MQ_HOST: ${ROOM_SERVICE_MQ_HOST}
      ROOM_SERVICE_MQ_PORT: ${ROOM_SERVICE_MQ_PORT}
      ROOM_SERVICE_MQ_VHOST: ${ROOM_SERVICE_MQ_VHOST}
      ROOM_SERVICE_MQ_SHOULD_USE_TLS: ${ROOM_SERVICE_MQ_SHOULD_USE_TLS}
      ROOM_SERVICE_MQ_EXCHANGE_NAME: ${ROOM_SERVICE_MQ_EXCHANGE_NAME}
      ROOM_SERVICE_MQ_QUEUE_NAME: ${ROOM_SERVICE_MQ_QUEUE_NAME}
      API_PORT: 9005
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${API_EXPOSED_PORT}:9005
    depends_on:
      - chat_service_message_broker
    restart: unless-stopped

networks:
  peerprep:
    name: peerprep
    external: true
