apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-message-broker-client-config-map
  namespace: peerprep
data:
  redis-username: default
  redis-host: redis-15784.c1.asia-northeast1-1.gce.cloud.redislabs.com
  redis-port: '15784'

  # This value should be "true" for actual deployment. The reason why it is
  # "false" is due to free tier database limitations.
  redis-should-use-tls: 'false'
