apiVersion: v1
kind: Service
metadata:
  name: chat-service-api-service
  namespace: peerprep
spec:
  selector:
    app: chat-service-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
